/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'
import { Route as TeamIdRouteImport } from './routes/team.$id'
import { Route as ProjectorIdRouteImport } from './routes/projector.$id'
import { Route as PlayerInviteTokenRouteImport } from './routes/player-invite.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AdminRegisterRouteImport } from './routes/admin.register'
import { Route as AdminIdRouteImport } from './routes/admin.$id'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdRoute = TeamIdRouteImport.update({
  id: '/team/$id',
  path: '/team/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectorIdRoute = ProjectorIdRouteImport.update({
  id: '/projector/$id',
  path: '/projector/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerInviteTokenRoute = PlayerInviteTokenRouteImport.update({
  id: '/player-invite/$token',
  path: '/player-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/admin/register',
  path: '/admin/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/register': typeof AdminRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/player-invite/$token': typeof PlayerInviteTokenRoute
  '/projector/$id': typeof ProjectorIdRoute
  '/team/$id': typeof TeamIdRoute
  '/watch/$slug': typeof WatchSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/register': typeof AdminRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/player-invite/$token': typeof PlayerInviteTokenRoute
  '/projector/$id': typeof ProjectorIdRoute
  '/team/$id': typeof TeamIdRoute
  '/watch/$slug': typeof WatchSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/register': typeof AdminRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/player-invite/$token': typeof PlayerInviteTokenRoute
  '/projector/$id': typeof ProjectorIdRoute
  '/team/$id': typeof TeamIdRoute
  '/watch/$slug': typeof WatchSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/super-admin'
    | '/admin/$id'
    | '/admin/register'
    | '/invite/$token'
    | '/player-invite/$token'
    | '/projector/$id'
    | '/team/$id'
    | '/watch/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/super-admin'
    | '/admin/$id'
    | '/admin/register'
    | '/invite/$token'
    | '/player-invite/$token'
    | '/projector/$id'
    | '/team/$id'
    | '/watch/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/super-admin'
    | '/admin/$id'
    | '/admin/register'
    | '/invite/$token'
    | '/player-invite/$token'
    | '/projector/$id'
    | '/team/$id'
    | '/watch/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuperAdminRoute: typeof SuperAdminRoute
  AdminIdRoute: typeof AdminIdRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PlayerInviteTokenRoute: typeof PlayerInviteTokenRoute
  ProjectorIdRoute: typeof ProjectorIdRoute
  TeamIdRoute: typeof TeamIdRoute
  WatchSlugRoute: typeof WatchSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id': {
      id: '/team/$id'
      path: '/team/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof TeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projector/$id': {
      id: '/projector/$id'
      path: '/projector/$id'
      fullPath: '/projector/$id'
      preLoaderRoute: typeof ProjectorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-invite/$token': {
      id: '/player-invite/$token'
      path: '/player-invite/$token'
      fullPath: '/player-invite/$token'
      preLoaderRoute: typeof PlayerInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$id': {
      id: '/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuperAdminRoute: SuperAdminRoute,
  AdminIdRoute: AdminIdRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
  PlayerInviteTokenRoute: PlayerInviteTokenRoute,
  ProjectorIdRoute: ProjectorIdRoute,
  TeamIdRoute: TeamIdRoute,
  WatchSlugRoute: WatchSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
